version: '3.9'

# docker compose --env-file .env.development.local -f docker-compose-{env}.yml --profile {profile} up -d {service(s)}
# docker compose --env-file .env.development.local -f docker-compose-dev.yml up -d

# -d = daemon mode
# tail /dev/null -f

services:

  nginx:
    container_name: nginx
    env_file: .env.development.local
    image: nginx:1.21
    volumes: 
      - ./nginx:/etc/nginx
    ports: 
      - ${NGINX_PORT}:${NGINX_PORT}

  backend:
    container_name: backend
    env_file: .env.development.local
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes: 
      - ./backend/app:/app
    ports: 
      - ${BACKEND_PORT}:${BACKEND_PORT}
    depends_on: 
      - postgres
    command: uvicorn main:app --reload --workers 2 --reload-dir /app --host 0.0.0.0 --port ${BACKEND_PORT}

  frontend:
    container_name: frontend
    env_file: .env.development.local
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes: 
      - ./frontend:/app
    ports: 
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    profiles: 
      - dev
      - frontend
    command: yarn dev

  postgres:
    container_name: postgres
    env_file: .env.development.local
    image: postgres:14
    restart: always
    volumes: 
      - postgres_data_dev:/var/lib/postgresql/data:cached
    ports: 
      - ${POSTGRES_PORT}:${POSTGRES_PORT}

  redis:
    container_name: redis
    env_file: .env.development.local
    image: redis
    volumes: 
      - redis_data_dev:/data # redis persistence
    ports: 
      - ${REDIS_PORT}:${REDIS_PORT}
    entrypoint: redis-server --appendonly yes

  pgadmin:
    container_name: pgadmin
    env_file: .env.development.local
    image: dpage/pgadmin4
    ports: 
      - ${PGADMIN_LISTEN_PORT}:80
    depends_on:
      - postgres
    profiles: 
      - dev
      - monitor

  pgmaint:
    container_name: pgmaint
    image: postgres:alpine
    env_file: .env.production.local
    working_dir: /app
    environment:
      - BASEDIR=/backups
      - DBLIST=hello alpha
      - DUMPPREFIX=ergopad
    volumes:
      - /backups/pgmaint:/backups
      - ./pgmaint/periodic/daily:/etc/periodic/daily/:ro
      - ./app:/app
    # command: start.sh
    profiles: 
      - dev
      - backup
    command: tail /dev/null -f

  aggregator:
    container_name: aggregator
    env_file: .env.development.local
    build:
      context: .
      dockerfile: Dockerfile.aggregator
    volumes: 
      - ./aggregator/app:/app # !! update for main docker-compose file
    ports: 
      - ${AGGREGATOR_PORT}:${AGGREGATOR_PORT}
    # command: uvicorn main:app --reload --workers 4 --reload-dir /app --host 0.0.0.0 --port ${AGGREGATOR_PORT}
    command: python main.py # TODO: automate with celery and API to call refreshes; infinite loop for now

  celery:
    container_name: celery
    env_file: .env.development.local
    build:
      context: .
      dockerfile: Dockerfile.celery
    environment:
      - CELERY_QUEUE
    volumes: 
      - ./celery/app:/app # !! update for main docker-compose file
    # command: celery --app main.celery worker --loglevel=${CELERY_LOGLEVEL} -Q ${CELERY_QUEUE} -c 1
    command: tail /dev/null -f

  flower:  
    container_name: flower
    env_file: .env.development.local
    image: mher/flower
    ports: 
      - ${FLOWER_PORT}:${FLOWER_PORT}
    depends_on:
      - redis
      - celery
    profiles: 
      - dev
      - monitor
    command: celery --broker=redis://redis:${REDIS_PORT}/0 flower --port=${FLOWER_PORT}

  # working really well 1/17/2022
  # - ?? will 3G be enough for mainnet
  # - alpine doesn't seem to work
  # - permission issues with ergoplatform pre-built (plus potentially additional unused image bytes)
  ergonode:
    container_name: ergonode
    env_file: .env.development.local
    image: openjdk # :alpine
    volumes:
      - ergonode_data:/opt/ergo/.ergo # blockchain data
      - ./ergonode/testnet.conf:${ERGONODE_CONF} # conf file
      - ./ergonode/ergo-4.0.20.2.jar:/opt/ergo/ergo.jar # jar executable
    ports:
      - ${ERGONODE_PORT}:${ERGONODE_PORT}
      - 9030:9030
    working_dir: /opt/ergo
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 90s
    logging:
        driver: "json-file"
        options:
            max-file: 5
            max-size: 10m
    command: java -jar -Xmx3G -Dlogback.stdout.level=${ERGONODE_LOGLEVEL} -Dlogback.file.level=${ERGONODE_LOGLEVEL} ergo.jar --${ERGONODE_NETWORK} -c ${ERGONODE_CONF}

  # only in dev.yml
  ergonode2:
    container_name: ergonode2
    env_file: .env.development.local
    image: openjdk # openjdk:alpine # ?? latest
    volumes:
      - ./ergonode/ergonode2:/opt/ergo # jar/conf
      - /ergo/testnet2/.ergo:/ergo/.ergo # blockchain
    ports:
      - ${ERGONODE2_PORT}:${ERGONODE_PORT}
    working_dir: /opt/ergo
    healthcheck:
      test: python healthcheck.py -p ${ERGONODE_PORT}
      interval: 5m # > block time; look for change in height
      timeout: 30s
      # retries: 5
      start_period: 30s
    logging:
        driver: "json-file"
        options:
            max-file: 5
            max-size: 10m
    profiles: 
      - dev
    command: java -jar -Xmx3G -Dlogback.stdout.level=${ERGONODE_LOGLEVEL} -Dlogback.file.level=${ERGONODE_LOGLEVEL} ergo.jar --${ERGONODE_NETWORK} -c ${ERGONODE2_CONF}

  # only in dev.yml
  ergonode3:
    container_name: ergonode3
    env_file: .env.development.local
    image: ergoplatform/ergo
    volumes:
      # - ./ergonode/ergonode2:/opt/ergo # jar/conf
      - /ergo/testnet3/.ergo:/home/ergo/.ergo # blockchain
      - ./ergonode/myergo.conf:/etc/myergo.conf
    ports:
      - 9054:9052
    environment:
      - MAX_HEAP=3G
    deploy:
      restart_policy:
        condition: any # One of none, on-failure or any (default: any).
        delay: 2s
        # max_attempts: 3
        window: 30s # How long to wait before deciding if a restart has succeeded, specified as a duration (default: decide immediately).
    # working_dir: /home/ergo
    logging:
        driver: "json-file"
        options:
            max-file: 5
            max-size: 10m
    profiles: 
      - dev
    # command: tail /dev/null -f
    entrypoint: tail /dev/null -f
    # entrypoint: java -jar -Xmx3G -Dlogback.stdout.level=${ERGONODE_LOGLEVEL} -Dlogback.file.level=${ERGONODE_LOGLEVEL} ergo.jar --${ERGONODE_NETWORK} -c /etc/myergo.conf

  # only in dev.yml
  ergonode4:
    container_name: ergonode4
    env_file: .env.production.local
    image: ergoplatform/ergo
    volumes:
      # - ./ergonode/ergonode2:/opt/ergo # jar/conf
      - ergonode4_data:/home/ergo/.ergo # blockchain
      - ./ergonode/myergo4.conf:/etc/myergo.conf
    ports:
      - 9055:9053
    environment:
      - MAX_HEAP=3G
    # working_dir: /home/ergo
    deploy:
      restart_policy:
        condition: on-failure # One of none, on-failure or any (default: any).
        delay: 2s
        # max_attempts: 3
        window: 30s # How long to wait before deciding if a restart has succeeded, specified as a duration (default: decide immediately).
    logging:
        driver: "json-file"
        options:
            max-file: 5
            max-size: 10m
    # command: tail /dev/null -f
    # entrypoint: tail /dev/null -f
    entrypoint: java -jar -Xmx5G -Dlogback.stdout.level=DEBUG -Dlogback.file.level=ERROR ergo.jar --mainnet -c /etc/myergo.conf

  assembler:
    container_name: assembler
    env_file: .env.development.local
    image: openjdk:11.0.13-jdk-buster
    volumes: 
      - ./assembler/:/opt/assembler
    ports: 
      - ${ASSEMBLER_PORT}:${ASSEMBLER_PORT}
    working_dir: /opt/assembler # set this if using image and not build
    logging:
        driver: "json-file"
        options:
            max-file: 5
            max-size: 10m
    command: java -jar -Dconfig.file=${ASSEMBLER_CONF} -Dhttp.port=${ASSEMBLER_PORT} ${ASSEMBLER_JAR}

#   ergostratum:
#     container_name: ergostratum
#     env_file: .env.development.local
#     build: 
#       context: .
#       dockerfile: Dockerfile.stratum
#     volumes: './stratum:/opt/ergo'
#     ports: 8008:8008 # stratum
#     depends_on: ergonode
#     command: nodemon ./tulip.js -e js # restart on js file changes

volumes:
  postgres_data_dev:
  redis_data_dev:
  ergonode4_data:
  ergonode_data: