version: '3.9'

# docker compose -f docker-compose-pgmaint.yml up pgmaint -d

services:
  pgmaint:
    container_name: pgmaint
    image: postgres:alpine
    env_file: .env.production.local # backup production
    working_dir: /app
    environment:
      - BASEDIR=/backups
      - DBLIST=ergopad alpha
      - DUMPPREFIX=ergopad
    volumes:
      - /backups/pgmaint:/backups
      - ./pgmaint/periodic/daily:/etc/periodic/daily/:ro
      - ./app:/app
    # command: start.sh
    command: tail /dev/null -f
