version: '3.9'

services:
  backend:
    container_name: backend
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes: 
      - ./backend/app:/app
    ports: 
      - ${BACKEND_PORT}:${BACKEND_PORT}
    command: uvicorn main:app --reload --workers 4 --reload-dir /app --host 0.0.0.0 --port 8000
