
version: '3.9'

services:

  pgmaint:
    image: postgres:alpine
    env_file: .env
    workdir: /app
    volumes:
      - /backups/pgmaint:/backups
      - ./app:/app
    command: start.sh
