name: Deploy

on:
  push:
    branches:
      - dev

  workflow_dispatch:

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install boto3
        run: pip3 install boto3

      - name: Deploy
        env:
          INSTANCE_ID: ${{ secrets.INSTANCE_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: python3 deploy.py
